In [25]:
import re
import pandas as pd
import numpy as np

path = "Mobiles Dataset (2025).csv"

In [26]:
df = pd.read_csv(path, encoding="latin1")

In [27]:
df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 224,999","INR 79,999","CNY 5,799",USD 799,"AED 2,799",2024
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 234,999","INR 84,999","CNY 6,099",USD 849,"AED 2,999",2024
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 244,999","INR 89,999","CNY 6,499",USD 899,"AED 3,199",2024
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 249,999","INR 89,999","CNY 6,199",USD 899,"AED 3,199",2024
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 259,999","INR 94,999","CNY 6,499",USD 949,"AED 3,399",2024

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    object
 3   RAM                        930 non-null    object
 4   Front Camera               930 non-null    object
 5   Back Camera                930 non-null    object
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    object
 8   Screen Size                930 non-null    object
 9   Launched Price (Pakistan)  930 non-null    object
 10  Launched Price (India)     930 non-null    object
 11  Launched Price (China)     930 non-null    object
 12  Launched Price (USA)       930 non-null    object
 13  Launched Price (Dubai)     930 non-null    object
 14  Launched Year              930 non-null    int64
dtypes: int64(1), object(14)
memory usage: 109.1+ KB

Transform obj to int and remove different symbols

In [29]:
def extract_number(value):
    if isinstance(value, str):
        value = re.sub(r'[^0-9.]', '', value.replace(',', ''))  # Remove non-numeric characters
        value = re.sub(r'\.(?=.*\.)', '', value)  # Keep only the first decimal point
        return float(value) if value else None
    return value

def extract_mp(value):
    if isinstance(value, str):
        mp_values = re.findall(r'\d+', value)  # Extract all numbers
        return float(mp_values[0]) if mp_values else None  # Take the first MP value
    return value

# Apply to both camera columns
df["Front Camera"] = df["Front Camera"].apply(extract_mp)
df["Back Camera"] = df["Back Camera"].apply(extract_mp)

# Clean numeric columns
df["RAM"] = df["RAM"].apply(extract_number)  # RAM in GB
df["Mobile Weight"] = df["Mobile Weight"].apply(extract_number)  # Weight in grams
df["Battery Capacity"] = df["Battery Capacity"].apply(extract_number)  # Battery in mAh
df["Screen Size"] = df["Screen Size"].apply(extract_number)  # Display size in inches

# Clean price columns
price_columns = ["Launched Price (Pakistan)", "Launched Price (India)", "Launched Price (China)",
                 "Launched Price (USA)", "Launched Price (Dubai)"]

for col in price_columns:
    df[col] = df[col].apply(extract_number)

# Save cleaned dataset
df.to_csv("Cleaned_Mobiles_Dataset.csv", index=False)

In [30]:
cleaned_df = pd.read_csv("Cleaned_Mobiles_Dataset.csv")
cleaned_df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,224999.0,79999.0,5799.0,799.0,2799.0,2024
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,234999.0,84999.0,6099.0,849.0,2999.0,2024
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,244999.0,89999.0,6499.0,899.0,3199.0,2024
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,249999.0,89999.0,6199.0,899.0,3199.0,2024
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,259999.0,94999.0,6499.0,949.0,3399.0,2024

In [31]:
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Name               930 non-null    object
 1   Model Name                 930 non-null    object
 2   Mobile Weight              930 non-null    float64
 3   RAM                        930 non-null    float64
 4   Front Camera               930 non-null    float64
 5   Back Camera                930 non-null    float64
 6   Processor                  930 non-null    object
 7   Battery Capacity           930 non-null    float64
 8   Screen Size                930 non-null    float64
 9   Launched Price (Pakistan)  929 non-null    float64
 10  Launched Price (India)     930 non-null    float64
 11  Launched Price (China)     930 non-null    float64
 12  Launched Price (USA)       930 non-null    float64
 13  Launched Price (Dubai)     930 non-null    float64
 14  Launched Year              930 non-null    int64
dtypes: float64(11), int64(1), object(3)
memory usage: 109.1+ KB

Generate random sales columns

In [32]:
cleaned_df['Sales'] = np.random.randint(100000, 1000001, size=len(df))
cleaned_df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year,Sales
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,224999.0,79999.0,5799.0,799.0,2799.0,2024,299849
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,234999.0,84999.0,6099.0,849.0,2999.0,2024,705534
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,244999.0,89999.0,6499.0,899.0,3199.0,2024,264551
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,249999.0,89999.0,6199.0,899.0,3199.0,2024,733939
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,259999.0,94999.0,6499.0,949.0,3399.0,2024,827763

Generate columns with random place

In [33]:
cities = ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"]

cleaned_df['City'] = np.random.choice(cities, size=len(df))

In [34]:
cleaned_df.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year,Sales,City
0,Apple,iPhone 16 128GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,224999.0,79999.0,5799.0,799.0,2799.0,2024,299849,Houston
1,Apple,iPhone 16 256GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,234999.0,84999.0,6099.0,849.0,2999.0,2024,705534,San Diego
2,Apple,iPhone 16 512GB,174.0,6.0,12.0,48.0,A17 Bionic,3600.0,6.1,244999.0,89999.0,6499.0,899.0,3199.0,2024,264551,Phoenix
3,Apple,iPhone 16 Plus 128GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,249999.0,89999.0,6199.0,899.0,3199.0,2024,733939,Houston
4,Apple,iPhone 16 Plus 256GB,203.0,6.0,12.0,48.0,A17 Bionic,4200.0,6.7,259999.0,94999.0,6499.0,949.0,3399.0,2024,827763,Dallas

In [35]:
# Save updated dataset
cleaned_df.to_csv("Cleaned_Mobiles_Dataset.csv", index=False)